### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by tshort** [ModiaSim/ModiaMath.jl#3]
It'd help to have this package registered. That would make it easier to enable Travis testing on Modia. (I don't see any reason not to register Modia, too.)

**Comment by MartinOtter** [comment]
Yes. I did not yet have time to figure out how to do this, but just saw that at some place a pull request has to be made. Can you do this as well? Then please, register (also Modia).

**Comment by tshort** [comment]
I suggest setting up [attobot](https://github.com/attobot/attobot). That is a service that automatically registers your package when you tag a release in GitHub (and it updates it every time you tag a new version). I can't set that up for you. It has to be an owner of this repository. The link above has good directions.

**Comment by MartinOtter** [comment]
Thanks. Will have a look.

**Comment by tshort** [comment]
Here's where the pull requests from attobot go when triggered:

https://github.com/JuliaLang/METADATA.jl/pulls
