### ISSUE TITLE
Use consistant indentation

### ISSUE THREAD

**Issue by ufechner7** [ModiaSim/ModiaMath.jl#5]
When looking at the code I noticed, that the indentation is not consistent:
Sometimes three and sometimes four spaces are used for indentation, sometimes even only one.
This should be made constant to make it easier to merge pull requests.
Further more I would suggest always to use a space after a "," .

**Comment by MartinOtter** [comment]
>When looking at the code I noticed, that the indentation is not consistent:
Sometimes three and sometimes four spaces are used for indentation, sometimes even only one. This should be made constant to make it easier to merge pull requests.

Usually, I use 3 spaces for indentation (and replace tabs by 3 spaces). Is there a particular convention used in Julia packages with regards to indentation?

> Further more I would suggest always to use a space after a "," .
Yes, this is my intention, but obviously not consequently done

**Comment by ufechner7** [comment]
Now that Modia.jl uses four spaces for indentation, wouldn't it make sense to do the same for this project?
(See: https://github.com/ModiaSim/Modia.jl/issues/20 )

**Comment by crlaugh** [comment]
I just submitted a pull request (#7) to address this; if this PR is accepted, we can close this issue.

**Comment by MartinOtter** [comment]
The pull request was accepted (so four spaces indentation was introduced)
